services:
  # db:
  #   container_name: test_db
  #   image: nouchka/sqlite3
  #   restart: always

  app:
    container_name: app
    # depends_on:
    #   - db
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - PORTS=${PORT}
    ports:
      - "3000:3000"
      - "3010:3012"
    # command: sh -c "node server/server.js & npm run build && npm run start"
    command: sh -c "node server/server.js && npm run build && npm run start"

