version: "3.8"
services:
  backend:
    container_name: node_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NEXT_PUBLIC_BACKEND_PORT}:4025"
    volumes:
      - ./app/database:/app/database
    command: sh -c "node server.js"
  
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${NEXT_PUBLIC_FRONTEND_PORT}
    ports:
      - "${NEXT_PUBLIC_FRONTEND_PORT}:4000"
    command: sh -c "npm run build && npm run start"
