version: '3.8'

services:
  db:
    container_name: sqllitedb
    image: nouchka/sqlite3
    restart: always
    environment:
      SQLLite_DB_PATH: /app/database/database.db
    volumes:
      - ./app/database:/app/database
    ports:
      - 3000:3000

  app:
    container_name: app
    depends_on:
      - db
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - 3009:3010
    command: sh -c "npx node server/server.js && npm run build && npm run start"
