version: '3.8'

services:
  db:
    container_name: sqllitedb
    image: keinos/sqlite3
    command: node server.js
    restart: always
    environment:
      DB_Path: ${SQLLite_DB_PATH}
    ports:
      - ${PORT}

  app:
    container_name: app
    depends_on:
      - db
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - ${PORT}
    command: node run server && npm run build
