services:
  backend:
    container_name: node_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${NEXT_PUBLIC_BACKEND_PORT}
      - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
      - NEXT_PUBLIC_FRONTEND_PORT=${NEXT_PUBLIC_FRONTEND_PORT}
      - SQLLite_DB_PATH=${SQLLite_DB_PATH}
      - NEXT_PUBLIC_APP=${NEXT_PUBLIC_APP}

    ports:
      - "${NEXT_PUBLIC_BACKEND_PORT}:4025"
    volumes:
      - ./app/database:/app/database
    command: sh -c "node server.js"
  
  app:
    container_name: app
    # depends_on:
    #   - db
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=${NEXT_PUBLIC_FRONTEND_PORT}
      - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
      - NEXT_PUBLIC_FRONTEND_PORT=${NEXT_PUBLIC_FRONTEND_PORT}
      - SQLLite_DB_PATH=${SQLLite_DB_PATH}
      - NEXT_PUBLIC_APP=${NEXT_PUBLIC_APP}
    ports:
      - "${NEXT_PUBLIC_FRONTEND_PORT}:4000"
    # command: sh -c "node server/server.js & npm run build && npm run start"
    command: sh -c "npm run build && npm run start"
    
