services:
  # db:
  #   container_name: test_db
  #   image: nouchka/sqlite3
  #   restart: always

  backend:
    container_name: node_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - ./app/database:/app/database
    command: sh -c "node server/server.js"
  app:
    container_name: app
    # depends_on:
    #   - db
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - PORTS=${PORT}
    ports:
      - "3000:3000"
    # command: sh -c "node server/server.js & npm run build && npm run start"
    command: sh -c "npm run build && npm run start"

