services:
  # db:
  #   container_name: test_db
  #   image: nouchka/sqlite3
  #   volumes:
  #     - ./app/database:/app/database  # Mount your local db folder to container
  #   command: sqlite3 /app/database/database.db  # Execute sqlite3 with the correct db path
  #   restart: always

  app:
    container_name: app
    # depends_on:
    #   - db
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 3010:3010
    command: sh -c "node server/server.js & npm run build && npm run start"
