name: 'Ticket Solution CI/CD'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      # Install npm dependencies
      - name: Install npm dependencies
        run: |
          npm install next react react-dom sqlite3 --save-dev typescript --save-dev @types/react @types/react-dom express cors helmet

      # Run Unit Tests
      - name: Run Unit Tests
        run: npm test

      # Check for vulnerabilities
      - name: Check for Vulnerabilities
        run: npm audit

      # Build the project
      - name: Build project
        if: success()
        run: npm run build

      # Build Docker Image
      - name: Construct Docker Image
        run: docker build -t craftapp:latest -f ../Dockerfile ../