name: 'Ticket Solution CI CD'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out repositry
      - name: Checks out resposity
        uses: actions/checkout@v3

      # Configure Node Versionk
      - name: Configure node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      # Set up npm dependencies
      - name: Configure npm
        run: |
          npm install next react react-dom next react react-dom sqlite3 --save-dev typescript --save-dev @types/react @types/react-dom
          express cors helmet

      # Run Build
      - name: Run NPM Build for optimised build
        run: npm run build

      # Run Unit Tests
      - name: Run Unit-Tests
        run: npm test
