name: "Ticket Solution CI CD"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out repositry
      - name: Checks out resposity
        uses: actions/checkout@v3

      # Configure Node Versionk
      - name: Configured node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18.17.1'
    
      # Set up npm dependences
      - name: set up npm
        run: npm install

      # Run Unit Tests
      - name: Run Unit-Tests
        run: npm test
